CREATE TABLE IF NOT EXISTS Mindcache (
    id         TEXT PRIMARY KEY,
    brief      TEXT NOT NULL,
    sourceUrls TEXT NOT NULL DEFAULT '[]',
    createdAt  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
